cmake_minimum_required(VERSION 4.1)
project(D0003E_devenv C)

set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_ASM_COMPILER avr-gcc)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)

set(CMAKE_C_STANDARD 11)

include_directories(lab4)
include_directories(lab4/gui)
include_directories(lab4/include)
include_directories(lab4/include/avr)
include_directories(lab4/include/compat)
include_directories(lab4/include/interrupt)
include_directories(lab4/include/sys)
include_directories(lab4/include/util)
include_directories(lab4/waves)

add_compile_options(-mmcu=atmega169 -O2)
add_link_options(-mmcu=atmega169)

add_executable(D0003E_devenv
        lab4/gui/graphics.c
        lab4/gui/graphics.h
        lab4/gui/joystick.c
        lab4/gui/joystick.h
        lab4/gui/lcd.c
        lab4/gui/lcd.h
        lab4/include/avr/boot.h
        lab4/include/avr/common.h
        lab4/include/avr/cpufunc.h
        lab4/include/avr/crc16.h
        lab4/include/avr/delay.h
        lab4/include/avr/eeprom.h
        lab4/include/avr/fuse.h
        lab4/include/avr/interrupt.h
        lab4/include/avr/io.h
        lab4/include/avr/io1200.h
        lab4/include/avr/io2313.h
        lab4/include/avr/io2323.h
        lab4/include/avr/io2333.h
        lab4/include/avr/io2343.h
        lab4/include/avr/io43u32x.h
        lab4/include/avr/io43u35x.h
        lab4/include/avr/io4414.h
        lab4/include/avr/io4433.h
        lab4/include/avr/io4434.h
        lab4/include/avr/io76c711.h
        lab4/include/avr/io8515.h
        lab4/include/avr/io8534.h
        lab4/include/avr/io8535.h
        lab4/include/avr/io86r401.h
        lab4/include/avr/io90pwm1.h
        lab4/include/avr/io90pwm161.h
        lab4/include/avr/io90pwm216.h
        lab4/include/avr/io90pwm2b.h
        lab4/include/avr/io90pwm316.h
        lab4/include/avr/io90pwm3b.h
        lab4/include/avr/io90pwm81.h
        lab4/include/avr/io90pwmx.h
        lab4/include/avr/io90scr100.h
        lab4/include/avr/ioa5272.h
        lab4/include/avr/ioa5505.h
        lab4/include/avr/ioa5702m322.h
        lab4/include/avr/ioa5782.h
        lab4/include/avr/ioa5790.h
        lab4/include/avr/ioa5790n.h
        lab4/include/avr/ioa5795.h
        lab4/include/avr/ioa5831.h
        lab4/include/avr/ioa6285.h
        lab4/include/avr/ioa6286.h
        lab4/include/avr/ioa6289.h
        lab4/include/avr/ioa6612c.h
        lab4/include/avr/ioa6613c.h
        lab4/include/avr/ioa6614q.h
        lab4/include/avr/ioa6616c.h
        lab4/include/avr/ioa6617c.h
        lab4/include/avr/ioa664251.h
        lab4/include/avr/ioat94k.h
        lab4/include/avr/iocan128.h
        lab4/include/avr/iocan32.h
        lab4/include/avr/iocan64.h
        lab4/include/avr/iocanxx.h
        lab4/include/avr/iom103.h
        lab4/include/avr/iom128.h
        lab4/include/avr/iom1280.h
        lab4/include/avr/iom1281.h
        lab4/include/avr/iom1284.h
        lab4/include/avr/iom1284p.h
        lab4/include/avr/iom1284rfr2.h
        lab4/include/avr/iom128a.h
        lab4/include/avr/iom128rfa1.h
        lab4/include/avr/iom128rfr2.h
        lab4/include/avr/iom16.h
        lab4/include/avr/iom161.h
        lab4/include/avr/iom162.h
        lab4/include/avr/iom163.h
        lab4/include/avr/iom164.h
        lab4/include/avr/iom164pa.h
        lab4/include/avr/iom165.h
        lab4/include/avr/iom165a.h
        lab4/include/avr/iom165p.h
        lab4/include/avr/iom165pa.h
        lab4/include/avr/iom168.h
        lab4/include/avr/iom168a.h
        lab4/include/avr/iom168p.h
        lab4/include/avr/iom168pa.h
        lab4/include/avr/iom169.h
        lab4/include/avr/iom169p.h
        lab4/include/avr/iom169pa.h
        lab4/include/avr/iom16a.h
        lab4/include/avr/iom16hva.h
        lab4/include/avr/iom16hva2.h
        lab4/include/avr/iom16hvb.h
        lab4/include/avr/iom16hvbrevb.h
        lab4/include/avr/iom16m1.h
        lab4/include/avr/iom16u2.h
        lab4/include/avr/iom16u4.h
        lab4/include/avr/iom2560.h
        lab4/include/avr/iom2561.h
        lab4/include/avr/iom2564rfr2.h
        lab4/include/avr/iom256rfr2.h
        lab4/include/avr/iom3000.h
        lab4/include/avr/iom32.h
        lab4/include/avr/iom323.h
        lab4/include/avr/iom324.h
        lab4/include/avr/iom324pa.h
        lab4/include/avr/iom325.h
        lab4/include/avr/iom3250.h
        lab4/include/avr/iom3250pa.h
        lab4/include/avr/iom325pa.h
        lab4/include/avr/iom328p.h
        lab4/include/avr/iom329.h
        lab4/include/avr/iom3290.h
        lab4/include/avr/iom3290pa.h
        lab4/include/avr/iom32a.h
        lab4/include/avr/iom32c1.h
        lab4/include/avr/iom32hvb.h
        lab4/include/avr/iom32hvbrevb.h
        lab4/include/avr/iom32m1.h
        lab4/include/avr/iom32u2.h
        lab4/include/avr/iom32u4.h
        lab4/include/avr/iom32u6.h
        lab4/include/avr/iom406.h
        lab4/include/avr/iom48.h
        lab4/include/avr/iom48a.h
        lab4/include/avr/iom48p.h
        lab4/include/avr/iom48pa.h
        lab4/include/avr/iom48pb.h
        lab4/include/avr/iom64.h
        lab4/include/avr/iom640.h
        lab4/include/avr/iom644.h
        lab4/include/avr/iom644a.h
        lab4/include/avr/iom644p.h
        lab4/include/avr/iom644pa.h
        lab4/include/avr/iom644rfr2.h
        lab4/include/avr/iom645.h
        lab4/include/avr/iom6450.h
        lab4/include/avr/iom649.h
        lab4/include/avr/iom6490.h
        lab4/include/avr/iom649p.h
        lab4/include/avr/iom64a.h
        lab4/include/avr/iom64c1.h
        lab4/include/avr/iom64hve.h
        lab4/include/avr/iom64hve2.h
        lab4/include/avr/iom64m1.h
        lab4/include/avr/iom64rfr2.h
        lab4/include/avr/iom8.h
        lab4/include/avr/iom8515.h
        lab4/include/avr/iom8535.h
        lab4/include/avr/iom88.h
        lab4/include/avr/iom88a.h
        lab4/include/avr/iom88p.h
        lab4/include/avr/iom88pa.h
        lab4/include/avr/iom88pb.h
        lab4/include/avr/iom8a.h
        lab4/include/avr/iom8hva.h
        lab4/include/avr/iom8u2.h
        lab4/include/avr/iomx8.h
        lab4/include/avr/iomxx0_1.h
        lab4/include/avr/iomxx4.h
        lab4/include/avr/iomxxhva.h
        lab4/include/avr/iotn10.h
        lab4/include/avr/iotn11.h
        lab4/include/avr/iotn12.h
        lab4/include/avr/iotn13.h
        lab4/include/avr/iotn13a.h
        lab4/include/avr/iotn15.h
        lab4/include/avr/iotn1634.h
        lab4/include/avr/iotn167.h
        lab4/include/avr/iotn20.h
        lab4/include/avr/iotn22.h
        lab4/include/avr/iotn2313.h
        lab4/include/avr/iotn2313a.h
        lab4/include/avr/iotn24.h
        lab4/include/avr/iotn24a.h
        lab4/include/avr/iotn25.h
        lab4/include/avr/iotn26.h
        lab4/include/avr/iotn261.h
        lab4/include/avr/iotn261a.h
        lab4/include/avr/iotn28.h
        lab4/include/avr/iotn4.h
        lab4/include/avr/iotn40.h
        lab4/include/avr/iotn4313.h
        lab4/include/avr/iotn43u.h
        lab4/include/avr/iotn44.h
        lab4/include/avr/iotn441.h
        lab4/include/avr/iotn44a.h
        lab4/include/avr/iotn45.h
        lab4/include/avr/iotn461.h
        lab4/include/avr/iotn461a.h
        lab4/include/avr/iotn48.h
        lab4/include/avr/iotn5.h
        lab4/include/avr/iotn828.h
        lab4/include/avr/iotn84.h
        lab4/include/avr/iotn841.h
        lab4/include/avr/iotn84a.h
        lab4/include/avr/iotn85.h
        lab4/include/avr/iotn861.h
        lab4/include/avr/iotn861a.h
        lab4/include/avr/iotn87.h
        lab4/include/avr/iotn88.h
        lab4/include/avr/iotn9.h
        lab4/include/avr/iotnx4.h
        lab4/include/avr/iotnx5.h
        lab4/include/avr/iotnx61.h
        lab4/include/avr/iousb1286.h
        lab4/include/avr/iousb1287.h
        lab4/include/avr/iousb162.h
        lab4/include/avr/iousb646.h
        lab4/include/avr/iousb647.h
        lab4/include/avr/iousb82.h
        lab4/include/avr/iousbxx2.h
        lab4/include/avr/iousbxx6_7.h
        lab4/include/avr/iox128a1.h
        lab4/include/avr/iox128a1u.h
        lab4/include/avr/iox128a3.h
        lab4/include/avr/iox128a3u.h
        lab4/include/avr/iox128a4u.h
        lab4/include/avr/iox128b1.h
        lab4/include/avr/iox128b3.h
        lab4/include/avr/iox128c3.h
        lab4/include/avr/iox128d3.h
        lab4/include/avr/iox128d4.h
        lab4/include/avr/iox16a4.h
        lab4/include/avr/iox16a4u.h
        lab4/include/avr/iox16c4.h
        lab4/include/avr/iox16d4.h
        lab4/include/avr/iox192a3.h
        lab4/include/avr/iox192a3u.h
        lab4/include/avr/iox192c3.h
        lab4/include/avr/iox192d3.h
        lab4/include/avr/iox256a3.h
        lab4/include/avr/iox256a3b.h
        lab4/include/avr/iox256a3bu.h
        lab4/include/avr/iox256a3u.h
        lab4/include/avr/iox256c3.h
        lab4/include/avr/iox256d3.h
        lab4/include/avr/iox32a4.h
        lab4/include/avr/iox32a4u.h
        lab4/include/avr/iox32c3.h
        lab4/include/avr/iox32c4.h
        lab4/include/avr/iox32d3.h
        lab4/include/avr/iox32d4.h
        lab4/include/avr/iox32e5.h
        lab4/include/avr/iox384c3.h
        lab4/include/avr/iox384d3.h
        lab4/include/avr/iox64a1.h
        lab4/include/avr/iox64a1u.h
        lab4/include/avr/iox64a3.h
        lab4/include/avr/iox64a3u.h
        lab4/include/avr/iox64a4u.h
        lab4/include/avr/iox64b1.h
        lab4/include/avr/iox64b3.h
        lab4/include/avr/iox64c3.h
        lab4/include/avr/iox64d3.h
        lab4/include/avr/iox64d4.h
        lab4/include/avr/iox8e5.h
        lab4/include/avr/lock.h
        lab4/include/avr/parity.h
        lab4/include/avr/pgmspace.h
        lab4/include/avr/portpins.h
        lab4/include/avr/power.h
        lab4/include/avr/sfr_defs.h
        lab4/include/avr/signal.h
        lab4/include/avr/signature.h
        lab4/include/avr/sleep.h
        lab4/include/avr/version.h
        lab4/include/avr/wdt.h
        lab4/include/avr/xmega.h
        lab4/include/compat/deprecated.h
        lab4/include/compat/ina90.h
        lab4/include/compat/twi.h
        lab4/include/interrupt/interrupt_avr8.h
        lab4/include/sys/types.h
        lab4/include/util/atomic.h
        lab4/include/util/crc16.h
        lab4/include/util/delay_basic.h
        lab4/include/util/eu_dst.h
        lab4/include/util/parity.h
        lab4/include/util/setbaud.h
        lab4/include/util/twi.h
        lab4/include/util/usa_dst.h
        lab4/include/alloca.h
        lab4/include/asf.h
        lab4/include/assert.h
        lab4/include/board.h
        lab4/include/compiler.h
        lab4/include/conf_board.h
        lab4/include/ctype.h
        lab4/include/errno.h
        lab4/include/fcntl.h
        lab4/include/interrupt.h
        lab4/include/inttypes.h
        lab4/include/locale.h
        lab4/include/math.h
        lab4/include/parts.h
        lab4/include/setjmp.h
        lab4/include/signal.h
        lab4/include/status_codes.h
        lab4/include/stdfix-avrlibc.h
        lab4/include/stdint.h
        lab4/include/stdio.h
        lab4/include/stdlib.h
        lab4/include/string.h
        lab4/include/time.h
        lab4/include/unistd.h
        lab4/include/user_board.h
        lab4/waves/generator.c
        lab4/waves/generator.h
        lab4/waves/writer.c
        lab4/waves/writer.h
        lab4/lab4.c
        lab4/TinyTimber.c
        lab4/TinyTimber.h)
